### ISSUE TITLE
 RuntimeError: time-out of 10000ms while waiting for the simulator

### ISSUE THREAD

**Issue by luckynote** [ucla-mobility/OpenCDA#117]
` python opencda.py -t platoon_joining_2lanefree_cosim`
OpenCDA Version: 0.1.0
load opendrive map '2lane_freeway_simplified.xodr'.
Traceback (most recent call last):
  File "/home/idriver/liutao/github/OpenCDA/opencda/scenario_testing/platoon_joining_2lanefree_cosim.py", line 42, in run_scenario
    sumo_file_parent_path=sumo_cfg)
  File "/home/idriver/liutao/github/OpenCDA/opencda/scenario_testing/utils/cosim_api.py", line 64, in __init__
    cav_world)
  File "/home/idriver/liutao/github/OpenCDA/opencda/scenario_testing/utils/sim_api.py", line 114, in __init__
    self.world = load_customized_world(xodr_path, self.client)
  File "/home/idriver/liutao/github/OpenCDA/opencda/scenario_testing/utils/customized_map_api.py", line 54, in load_customized_world
    enable_mesh_visibility=True))
RuntimeError: time-out of 10000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "opencda.py", line 56, in <module>
    main()
  File "opencda.py", line 51, in main
    scenario_runner(opt, config_yaml)
  File "/home/idriver/liutao/github/OpenCDA/opencda/scenario_testing/platoon_joining_2lanefree_cosim.py", line 86, in run_scenario
    eval_manager.evaluate()
UnboundLocalError: local variable 'eval_manager' referenced before assignment

**Comment by luckynote** [comment]
And other command has same problem.

**Comment by DerrickXuNu** [comment]
what is the carla version you are using?

**Comment by DerrickXuNu** [comment]
> And other command has same problem.

Which command do you refer? Could you be more specific?

**Comment by luckynote** [comment]
> what is the carla version you are using?

[Ubuntu] CARLA_0.9.11.tar.gz
[Ubuntu] AdditionalMaps_0.9.11.tar.gz

**Comment by luckynote** [comment]
> > And other command has same problem.
> 
> Which command do you refer? Could you be more specific?
Quick Start: Single Vehicle Test & Cooperative Driving Test.

**Comment by DerrickXuNu** [comment]
It seems that you can not connect to the CARLA server. Can you make sure:
1) Your CARLA server is running normally
2) You don't have any other scripts using the same Client port running
If both fits, can you try to restart the CARLA server?

**Comment by wx983** [comment]
> 

But how to see the present version of carla?   I used 'git checkout tags/0.9.12 -b <branch_name>'  when installing it, but I don't know how to check the version
