### ISSUE TITLE
Error during the openCDA installation

### ISSUE THREAD

**Issue by Icegui** [ucla-mobility/OpenCDA#225]
Hello, I'm trying to install opencda but I keep getting the following error when I run "docker build -t opencda_container ":

<img width="856" alt="Screenshot 2024-06-28 123740" src="https://github.com/ucla-mobility/OpenCDA/assets/171645509/69899f0f-e4b2-42b3-bc12-be0e8fd772eb">

It seem like my computer cannot connect to the  https://carla-releases.s3.eu-west-3.amazonaws.com/Linux/CARLA_0.9.13.tar.gz server for some reasons but I do not understqnd why>.

**Comment by Icegui** [comment]
I have manage this problem but everytime I try running a scenario in OpenCDA I get the error message: 
Traceback (most recent call last):
  File "/home/guillaume_h/OpenCDA/opencda/scenario_testing/single_2lanefree_carla.py", line 33, in run_scenario
    scenario_manager = sim_api.ScenarioManager(scenario_params,
  File "/home/guillaume_h/OpenCDA/opencda/scenario_testing/utils/sim_api.py", line 190, in __init__
    self.world = load_customized_world(xodr_path, self.client)
  File "/home/guillaume_h/OpenCDA/opencda/scenario_testing/utils/customized_map_api.py", line 50, in load_customized_world
    world = client.generate_opendrive_world(
RuntimeError: time-out of 10000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
I'm using WSL2 and Ubuntu 18.04. I try running Carla on Windows and OpenCDA on wsl but I still go the same message error.
